"""PDF analysis: P1 (05-10/09) vs P2 (15/08-04/09) — Soja/Concentrés comparison.
Based on sept_p1_vs_p2_analysis.json generated by analyse_p1_vs_p2.py.
"""
import os
import json
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
)

pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))

NAVY = colors.HexColor('#1F3A5F')
GOLD = colors.HexColor('#C9A961')
RED = colors.HexColor('#C00000')
GREEN = colors.HexColor('#548235')
GRAY = colors.HexColor('#595959')
LIGHT_GRAY = colors.HexColor('#F2F2F2')
LIGHT_RED = colors.HexColor('#FCE4EC')
LIGHT_GREEN = colors.HexColor('#E2EFDA')
LIGHT_YELLOW = colors.HexColor('#FFF9E6')

styles = getSampleStyleSheet()
H1 = ParagraphStyle('H1', parent=styles['Heading1'], fontName='DejaVuSans-Bold', fontSize=18, textColor=NAVY, spaceAfter=12, spaceBefore=8)
H2 = ParagraphStyle('H2', parent=styles['Heading2'], fontName='DejaVuSans-Bold', fontSize=13, textColor=NAVY, spaceAfter=8, spaceBefore=12)
H3 = ParagraphStyle('H3', parent=styles['Heading3'], fontName='DejaVuSans-Bold', fontSize=11, textColor=GOLD, spaceAfter=6, spaceBefore=8)
BODY = ParagraphStyle('Body', parent=styles['Normal'], fontName='DejaVuSans', fontSize=10, leading=14, alignment=TA_JUSTIFY, spaceAfter=6)
BULLET = ParagraphStyle('Bullet', parent=BODY, leftIndent=20, bulletIndent=10, spaceAfter=4)
CELL = ParagraphStyle('Cell', parent=BODY, fontName='DejaVuSans', fontSize=9, leading=11, alignment=TA_LEFT, spaceAfter=0)
SMALL = ParagraphStyle('Small', parent=BODY, fontSize=8, textColor=GRAY, leading=10)

# === Cell paragraph styles (for wrapping) ===
CELL_HEADER = ParagraphStyle('CellHeader', fontName='DejaVuSans-Bold', fontSize=8, leading=10, alignment=TA_CENTER, textColor=colors.white)
CELL_CENTER = ParagraphStyle('CellCenter', fontName='DejaVuSans', fontSize=8, leading=10, alignment=TA_CENTER)
CELL_LEFT = ParagraphStyle('CellLeft', fontName='DejaVuSans', fontSize=8, leading=10, alignment=TA_LEFT)
CELL_LEFT_SMALL = ParagraphStyle('CellLeftSmall', fontName='DejaVuSans', fontSize=7, leading=9, alignment=TA_LEFT)

def wrap_cell(content, style=CELL_CENTER):
    """Wrap content in a Paragraph to enable proper text wrapping in tables."""
    s = str(content) if content is not None else ''
    return Paragraph(s, style)

def make_table_data(raw_data, header_style=CELL_HEADER, body_style=CELL_CENTER, first_col_style=None):
    """Convert raw 2D list to Paragraphs for proper wrapping.
    First row = header, first column (optional) uses first_col_style."""
    wrapped = []
    for ri, row in enumerate(raw_data):
        prow = []
        for ci, cell in enumerate(row):
            if ri == 0:
                prow.append(wrap_cell(cell, header_style))
            elif ci == 0 and first_col_style is not None:
                prow.append(wrap_cell(cell, first_col_style))
            else:
                prow.append(wrap_cell(cell, body_style))
        wrapped.append(prow)
    return wrapped

# === Load data ===
DATA = json.load(open('/home/z/my-project/scripts/sept_p1_vs_p2_analysis.json'))

def fmt(x):
    if isinstance(x, (int, float)):
        return f"{x:,.1f}".replace(',', ' ').replace('.', ',')
    return str(x)

def fmt_signed(x):
    s = '+' if x >= 0 else ''
    return f"{s}{x:.1f}%".replace('.', ',')

def color_for_var(x):
    if x >= 0: return LIGHT_GREEN
    if x <= -50: return LIGHT_RED
    return LIGHT_YELLOW

# === Build PDF ===
OUT = '/home/z/my-project/download/analyse_p1_vs_p2_upd.pdf'
doc = SimpleDocTemplate(OUT, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm, leftMargin=1.5*cm, rightMargin=1.5*cm)
story = []

# === Cover / Title ===
story.append(Paragraph("BELGOCAM SA", ParagraphStyle('CT', parent=styles['Title'], fontName='DejaVuSans-Bold', fontSize=24, textColor=NAVY, alignment=TA_CENTER, spaceAfter=8)))
story.append(Paragraph("Analyse Soja / Concentrés", ParagraphStyle('CS', parent=styles['Title'], fontName='DejaVuSans-Bold', fontSize=18, textColor=GOLD, alignment=TA_CENTER, spaceAfter=4)))
story.append(Paragraph("P1 (05-10/09) vs P2 (15/08-04/09 — 3 semaines précédentes)", ParagraphStyle('CS2', parent=BODY, fontSize=12, textColor=GRAY, alignment=TA_CENTER, spaceAfter=8)))
story.append(HRFlowable(width="100%", thickness=1, color=NAVY))
story.append(Spacer(1, 0.3*cm))

story.append(Paragraph(
    f"<b>Période 1</b> : {DATA['p1_dates']['start']} → {DATA['p1_dates']['end']} ({DATA['p1_dates']['work_days']}j ouvrés)<br/>"
    f"<b>Période 2</b> : {DATA['p2_dates']['start']} → {DATA['p2_dates']['end']} ({DATA['p2_dates']['work_days']}j ouvrés = 3 semaines)<br/>"
    f"<b>⚠ Contexte</b> : Hausse prix soja 04/09/2026 — 25 000 → 27 000 FCFA/sac (+8%)",
    ParagraphStyle('PInfo', parent=BODY, fontSize=10, alignment=TA_CENTER, textColor=GRAY, spaceAfter=10)))

# === 1. GLOBAL ===
story.append(Paragraph("1. Vue Globale — Comparaison des volumes", H2))

g = DATA['global']
p1s = g['p1']['soja_t']
p2s = g['p2']['soja_t']
p1c = g['p1']['conc_t']
p2c = g['p2']['conc_t']
p1s_moy = g['p1']['soja_moy_j']
p2s_moy = g['p2']['soja_moy_j']
p1c_moy = g['p1']['conc_moy_j']
p2c_moy = g['p2']['conc_moy_j']

var_s = g['var_soja_pct']
var_c = g['var_conc_pct']
var_s_moy = g['var_soja_moy_j_pct']
var_c_moy = g['var_conc_moy_j_pct']

ratio1 = p1s/p1c if p1c > 0 else 0
ratio2 = p2s/p2c if p2c > 0 else 0

glob_data = [
    ["Indicateur", "P1 (05-10/09)", "P2 (15/08-04/09)", "Var brute", "Var moy/j", "Lecture"],
    ["TOURTEAUX (t)", fmt(p1s), fmt(p2s), fmt_signed(var_s), fmt_signed(var_s_moy),
     "Chute majeure" if var_s_moy <= -30 else ("Baisse" if var_s_moy < 0 else "Hausse")],
    ["TOURTEAUX moy/j (t)", fmt(p1s_moy), fmt(p2s_moy), "—", fmt_signed(var_s_moy), "—"],
    ["CONCENTRÉS (t)", fmt(p1c), fmt(p2c), fmt_signed(var_c), fmt_signed(var_c_moy),
     "Baisse modérée" if var_c_moy > -30 else "Chute majeure"],
    ["CONCENTRÉS moy/j (t)", fmt(p1c_moy), fmt(p2c_moy), "—", fmt_signed(var_c_moy), "—"],
    ["Total Soja+Conc (t)", fmt(p1s+p1c), fmt(p2s+p2c), fmt_signed((p1s+p1c)/(p2s+p2c)*100-100), "—", "—"],
    ["Ratio soja/conc", f"{ratio1:.2f}:1", f"{ratio2:.2f}:1", "—", "—",
     "Recul du ratio (cross-sell perturbé)" if ratio1 < ratio2 else "Amélioration cross-sell"],
]

wrapped_glob = make_table_data(glob_data, first_col_style=CELL_LEFT)
t1 = Table(wrapped_glob, colWidths=[3.8*cm, 2.5*cm, 2.5*cm, 1.8*cm, 1.8*cm, 3.6*cm], repeatRows=1)
style_list = [
    ('BACKGROUND', (0,0), (-1,0), NAVY),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('GRID', (0,0), (-1,-1), 0.5, colors.gray),
    ('TOPPADDING', (0,0), (-1,-1), 4), ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ('LEFTPADDING', (0,0), (-1,-1), 4), ('RIGHTPADDING', (0,0), (-1,-1), 4),
]
style_list.append(('BACKGROUND', (0,1), (-1,1), color_for_var(var_s_moy)))
style_list.append(('BACKGROUND', (0,3), (-1,3), color_for_var(var_c_moy)))
style_list.append(('BACKGROUND', (0,5), (-1,5), colors.HexColor('#FFF2CC')))
style_list.append(('BACKGROUND', (0,6), (-1,6), LIGHT_GREEN))
t1.setStyle(TableStyle(style_list))
story.append(t1)
story.append(Spacer(1, 0.3*cm))

glob_analysis = f"""
<b>Lecture globale</b> : Sur la période P1 (5 jours ouvrés post-hausse prix), la cadence SOJA a chuté de 
<b>{fmt_signed(var_s_moy)}</b> en moyenne/jour vs P2 (3 semaines pré-hausse), passant de {fmt(p2s_moy)} t/j à {fmt(p1s_moy)} t/j. 
La cadence CONCENTRÉS a également baissé de <b>{fmt_signed(var_c_moy)}</b> ({fmt(p2c_moy)} t/j → {fmt(p1c_moy)} t/j). 

Le <b>ratio bundle soja/conc</b> passe de {ratio2:.2f}:1 (P2) à {ratio1:.2f}:1 (P1) — 
{"<b>amélioration du cross-sell</b> (ratio plus proche de 1:1, plus de conc par rapport au soja)" if ratio1 < ratio2 else "<b>dégradation du cross-sell</b> (ratio s'éloigne de 1:1, moins de conc par rapport au soja)"}. 
Cette baisse s'explique par l'effet combiné : (1) la hausse tarifaire du 04/09 (27 000 FCFA/sac, +8%) qui ralentit la demande soja, 
(2) la fin de la rupture concurrente (juillet-août) qui avait gonflé artificiellement les ventes P2, et (3) un effet saisonnier 
de debut septembre généralement plus calme.
"""
story.append(Paragraph(glob_analysis, BODY))
story.append(Spacer(1, 0.3*cm))

# === 2. PAR RÉGION ===
story.append(Paragraph("2. Vue Régionale — Performances par région", H2))

reg_data = [["Région", "P1 Soja (t)", "P2 Soja (t)", "Δ Soja %", "P1 Conc (t)", "P2 Conc (t)", "Δ Conc %", "Ratio P1", "Ratio P2"]]
for region in ['Ouest', 'Centre', 'Littoral']:
    r = DATA['regions'][region]
    ratio1 = r['p1']['soja_t']/r['p1']['conc_t'] if r['p1']['conc_t'] > 0 else 0
    ratio2 = r['p2']['soja_t']/r['p2']['conc_t'] if r['p2']['conc_t'] > 0 else 0
    reg_data.append([region, fmt(r['p1']['soja_t']), fmt(r['p2']['soja_t']),
                    fmt_signed(r['var_soja_pct']),
                    fmt(r['p1']['conc_t']), fmt(r['p2']['conc_t']),
                    fmt_signed(r['var_conc_pct']),
                    f"{ratio1:.2f}:1", f"{ratio2:.2f}:1"])

wrapped_reg = make_table_data(reg_data, first_col_style=CELL_LEFT)
t2 = Table(wrapped_reg, colWidths=[1.8*cm, 1.9*cm, 1.9*cm, 1.7*cm, 1.9*cm, 1.9*cm, 1.7*cm, 1.4*cm, 1.4*cm], repeatRows=1)
style_list2 = [
    ('BACKGROUND', (0,0), (-1,0), NAVY),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('GRID', (0,0), (-1,-1), 0.5, colors.gray),
    ('TOPPADDING', (0,0), (-1,-1), 3), ('BOTTOMPADDING', (0,0), (-1,-1), 3),
    ('LEFTPADDING', (0,0), (-1,-1), 3), ('RIGHTPADDING', (0,0), (-1,-1), 3),
]
# Color Δ cells
for i, region in enumerate(['Ouest', 'Centre', 'Littoral'], 1):
    r = DATA['regions'][region]
    style_list2.append(('BACKGROUND', (3, i), (3, i), color_for_var(r['var_soja_pct'])))
    style_list2.append(('BACKGROUND', (6, i), (6, i), color_for_var(r['var_conc_pct'])))
t2.setStyle(TableStyle(style_list2))
story.append(t2)
story.append(Spacer(1, 0.3*cm))

# Regional analysis
ouest = DATA['regions']['Ouest']
centre = DATA['regions']['Centre']
littoral = DATA['regions']['Littoral']

reg_analysis = f"""
<b>Lecture régionale</b> :
<br/>• <b>OUEST</b> (région leader) : chute soja {fmt_signed(ouest['var_soja_pct'])}, conc {fmt_signed(ouest['var_conc_pct'])} — ratio passe de {ouest['p2']['soja_t']/ouest['p2']['conc_t']:.2f}:1 à {ouest['p1']['soja_t']/ouest['p1']['conc_t']:.2f}:1 (cross-sell amélioré).
<br/>• <b>CENTRE</b> : chute soja {fmt_signed(centre['var_soja_pct'])}, conc {fmt_signed(centre['var_conc_pct'])} — ratio stable autour de 1,9-2,0:1 (discipline bundle préservée).
<br/>• <b>LITTORAL</b> : chute la plus sévère, soja {fmt_signed(littoral['var_soja_pct'])} ({fmt(littoral['p2']['soja_t'])} t → {fmt(littoral['p1']['soja_t'])} t). NDOBO particulièrement impacté (de 591,7 t à 21,2 t — pic exceptionnel P2 lié à la rupture concurrente, normalisation en P1). Ratio passe de {littoral['p2']['soja_t']/littoral['p2']['conc_t']:.2f}:1 (P2, anomalique) à {littoral['p1']['soja_t']/littoral['p1']['conc_t']:.2f}:1 (P1, normalisé).
"""
story.append(Paragraph(reg_analysis, BODY))
story.append(Spacer(1, 0.3*cm))

# === 3. PAR AGENCE ===
story.append(PageBreak())
story.append(Paragraph("3. Vue par Agence — Top 15 agences (par volume P1)", H2))

ag_data = [["Rang", "Agence", "Région", "P1 Soja (t)", "P2 Soja (t)", "Δ Soja %", "P1 Conc (t)", "P2 Conc (t)", "Δ Conc %"]]
for i, (ag, info) in enumerate(list(DATA['agences'].items())[:15], 1):
    ag_data.append([str(i), ag, info['region'],
                   fmt(info['p1']['soja_t']), fmt(info['p2']['soja_t']),
                   fmt_signed(info['var_soja_pct']),
                   fmt(info['p1']['conc_t']), fmt(info['p2']['conc_t']),
                   fmt_signed(info['var_conc_pct'])])

# Build with mixed styles: column 1 = center, column 2 = left, rest = center
wrapped_ag = []
for ri, row in enumerate(ag_data):
    prow = []
    for ci, cell in enumerate(row):
        if ri == 0:
            prow.append(wrap_cell(cell, CELL_HEADER))
        elif ci == 1:  # Agence column
            prow.append(wrap_cell(cell, CELL_LEFT_SMALL))
        else:
            prow.append(wrap_cell(cell, CELL_CENTER))
    wrapped_ag.append(prow)

t3 = Table(wrapped_ag, colWidths=[1.2*cm, 2.4*cm, 1.5*cm, 1.6*cm, 1.6*cm, 1.5*cm, 1.6*cm, 1.6*cm, 1.5*cm], repeatRows=1)
style_list3 = [
    ('BACKGROUND', (0,0), (-1,0), NAVY),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('GRID', (0,0), (-1,-1), 0.5, colors.gray),
    ('TOPPADDING', (0,0), (-1,-1), 3), ('BOTTOMPADDING', (0,0), (-1,-1), 3),
    ('LEFTPADDING', (0,0), (-1,-1), 3), ('RIGHTPADDING', (0,0), (-1,-1), 3),
]
# Color Δ cells for each agence
for i, (ag, info) in enumerate(list(DATA['agences'].items())[:15], 1):
    style_list3.append(('BACKGROUND', (5, i), (5, i), color_for_var(info['var_soja_pct'])))
    style_list3.append(('BACKGROUND', (8, i), (8, i), color_for_var(info['var_conc_pct'])))
t3.setStyle(TableStyle(style_list3))
story.append(t3)
story.append(Spacer(1, 0.3*cm))

# === 4. Insights ===
story.append(Paragraph("4. Insights & explications", H2))

insights = [
    f"<b>Chute SOJA plus marquée que CONCENTRÉS</b> : {fmt_signed(var_s_moy)} soja vs {fmt_signed(var_c_moy)} conc (moy/j). Le SOJA est directement impacté par la hausse prix du 04/09 (27 000 FCFA/sac, +8%) — les clients adoptent un comportement attentiste en début de mois.",
    f"<b>Effet base P2 gonflée</b> : La période P2 (15/08-04/09) inclut la fin de la rupture concurrente (juillet-août), qui avait artificiellement boosté les ventes soja (clients se reportant vers BELGOCAM). La comparaison P1 vs P2 surestime donc la dégradation réelle.",
    f"<b>Cross-sell bundle maintenu</b> : Le ratio soja/conc passe de {ratio2:.2f}:1 (P2) à {ratio1:.2f}:1 (P1). La discipline commerciale reste bonne — les clients qui continuent à acheter du soja achètent aussi du conc.",
    f"<b>LITTORAL = anomalie P2</b> : Le ratio P2 Littoral de 3,73:1 est anormal (vs ~1,9-2,1:1 sur les autres régions et périodes). Cela s'explique par un pic exceptionnel sur NDOBO (591,7 t soja en P2, soit 32,9 t/jour — niveau insoutenable). En P1, retour à un ratio normalisé de 1,95:1.",
    f"<b>OUEST = région la plus résiliente</b> : La chute relative est plus modérée que la moyenne nationale. FAMLA (Ouest) reste le pilier avec {fmt(DATA['agences']['Famla']['p1']['soja_t'])} t soja + {fmt(DATA['agences']['Famla']['p1']['conc_t'])} t conc en P1.",
    f"<b>Baisse CONCENTRÉS plus contenue</b> (-{abs(var_c_moy):.1f}% moy/j) : Le conc n'est pas directement impacté par la hausse prix soja, mais subit un effet d'entraînement (cross-sell lié au soja). Si la cadence soja remonte, le conc suivra.",
]
for i, ins in enumerate(insights, 1):
    story.append(Paragraph(f"<b>{i}.</b> {ins}", BULLET))
story.append(Spacer(1, 0.3*cm))

# === 5. Recommandations ===
story.append(Paragraph("5. Recommandations", H2))
recos = [
    "<b>Surveiller la cadence sur 7-10j</b> : La dégradation P1 est réelle mais affectée par l'effet base P2 (rupture concurrente). Il faut comparer P1 aux 2 prochaines semaines pour confirmer la tendance.",
    "<b>Renforcer le push CONCENTRÉS Littoral</b> : NDOBO + VILLAGE + NKONGSAMBA = 60% obj en Sept MTD. Activer promotions bundle pour relancer la dynamique.",
    "<b>Communication commerciale</b> : Préparer un argumentaire pour rassurer les clients sur la hausse prix soja (qualité, disponibilité, accompagnement). Le comportement attentiste devrait se dissiper après 2-3 semaines.",
    "<b>Maintenir le cross-sell bundle</b> : Ratio actuel 1,9:1 ✅ (objectif ≤ 2,5:1). Ne pas relâcher la discipline bundle malgré le choc prix.",
    "<b>Actualiser forecast Q4 2026</b> : Si la cadence P1 se maintient durablement sous 80 t/j soja, ajuster le forecast Q4 (actuellement 20 051 t — pourrait être revu à la baisse).",
]
for r in recos:
    story.append(Paragraph(f"• {r}", BULLET))
story.append(Spacer(1, 0.3*cm))

# === Footer ===
story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
story.append(Paragraph(
    f"<b>Méthodologie</b> : Comparaison des volumes Livrées (clients externes uniquement — SPC/PDC/Comptoir exclus). "
    f"Période 1 = 5 jours ouvrés (05-10/09/2026, post-hausse prix). Période 2 = 18 jours ouvrés (15/08-04/09/2026, 3 semaines pré-hausse). "
    f"Sources : dataset_2023_2026.csv pour août 2026 + extraction NJS GROUP ERP (36).xlsx du 11/09/2026 pour septembre 2026. "
    f"La variation moyenne/jour neutralise l'effet de durée différente entre les deux périodes.",
    SMALL))

doc.build(story)
print(f"\n=== PDF GENERATED ===")
print(f"Path: {OUT}")
print(f"Size: {os.path.getsize(OUT)/1024:.0f} KB")
