"""PDF analysis: Trend over 4 weekly periods (P1, W-1, W-2, W-3).
Same number of working days per period = fair comparison.
Based on sept_trend_analysis.json generated by analyse_trend.py.
"""
import os
import json
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak, Image
)

pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))

NAVY = colors.HexColor('#1F3A5F')
GOLD = colors.HexColor('#C9A961')
RED = colors.HexColor('#C00000')
GREEN = colors.HexColor('#548235')
GRAY = colors.HexColor('#595959')
LIGHT_GRAY = colors.HexColor('#F2F2F2')
LIGHT_RED = colors.HexColor('#FCE4EC')
LIGHT_GREEN = colors.HexColor('#E2EFDA')
LIGHT_YELLOW = colors.HexColor('#FFF9E6')

styles = getSampleStyleSheet()
H1 = ParagraphStyle('H1', parent=styles['Heading1'], fontName='DejaVuSans-Bold', fontSize=18, textColor=NAVY, spaceAfter=12, spaceBefore=8)
H2 = ParagraphStyle('H2', parent=styles['Heading2'], fontName='DejaVuSans-Bold', fontSize=13, textColor=NAVY, spaceAfter=8, spaceBefore=12)
H3 = ParagraphStyle('H3', parent=styles['Heading3'], fontName='DejaVuSans-Bold', fontSize=11, textColor=GOLD, spaceAfter=6, spaceBefore=8)
BODY = ParagraphStyle('Body', parent=styles['Normal'], fontName='DejaVuSans', fontSize=10, leading=14, alignment=TA_JUSTIFY, spaceAfter=6)
BULLET = ParagraphStyle('Bullet', parent=BODY, leftIndent=20, bulletIndent=10, spaceAfter=4)
SMALL = ParagraphStyle('Small', parent=BODY, fontSize=8, textColor=GRAY, leading=10)

# === Cell paragraph styles ===
CELL_HEADER = ParagraphStyle('CellHeader', fontName='DejaVuSans-Bold', fontSize=8, leading=10, alignment=TA_CENTER, textColor=colors.white)
CELL_CENTER = ParagraphStyle('CellCenter', fontName='DejaVuSans', fontSize=8, leading=10, alignment=TA_CENTER)
CELL_LEFT = ParagraphStyle('CellLeft', fontName='DejaVuSans', fontSize=8, leading=10, alignment=TA_LEFT)
CELL_LEFT_SMALL = ParagraphStyle('CellLeftSmall', fontName='DejaVuSans', fontSize=7, leading=9, alignment=TA_LEFT)

def wrap_cell(content, style=CELL_CENTER):
    s = str(content) if content is not None else ''
    return Paragraph(s, style)

# === Load data ===
DATA = json.load(open('/home/z/my-project/scripts/sept_trend_analysis.json'))
PERIODS_ORDER = ['W-3', 'W-2', 'W-1', 'P1']

def fmt(x):
    if isinstance(x, (int, float)):
        return f"{x:,.1f}".replace(',', ' ').replace('.', ',')
    return str(x)

def fmt_signed(x):
    s = '+' if x >= 0 else ''
    return f"{s}{x:.1f}%".replace('.', ',')

def color_for_var(x):
    if x >= 5: return LIGHT_GREEN
    if x <= -20: return LIGHT_RED
    if x <= -5: return LIGHT_YELLOW
    return LIGHT_GRAY

# === Build PDF ===
OUT = '/home/z/my-project/download/analyse_trend_upd.pdf'
doc = SimpleDocTemplate(OUT, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm, leftMargin=1.5*cm, rightMargin=1.5*cm)
story = []

# === Cover / Title ===
story.append(Paragraph("BELGOCAM SA", ParagraphStyle('CT', parent=styles['Title'], fontName='DejaVuSans-Bold', fontSize=22, textColor=NAVY, alignment=TA_CENTER, spaceAfter=6)))
story.append(Paragraph("Analyse Soja/Concentrés — Tendance sur 4 semaines", ParagraphStyle('CS', parent=styles['Title'], fontName='DejaVuSans-Bold', fontSize=16, textColor=GOLD, alignment=TA_CENTER, spaceAfter=4)))
story.append(Paragraph("P1 (05-10/09) vs W-1, W-2, W-3 (3 semaines précédentes)", ParagraphStyle('CS2', parent=BODY, fontSize=11, textColor=GRAY, alignment=TA_CENTER, spaceAfter=8)))
story.append(HRFlowable(width="100%", thickness=1, color=NAVY))
story.append(Spacer(1, 0.3*cm))

# Periods info
periods_info = " | ".join([f"{p['name']} = {p['dates']['label']} ({p['dates']['work_days']}j ouvrés)" for p in DATA['periods']])
story.append(Paragraph(f"<b>Périodes comparées (mêmes nb de jours = 5j ouvrés lun-sam)</b> : {periods_info}", 
                       ParagraphStyle('PInfo', parent=BODY, fontSize=9, alignment=TA_CENTER, textColor=GRAY, spaceAfter=4)))
story.append(Paragraph(f"<b>⚠ Contexte</b> : Hausse prix soja 04/09/2026 — 25 000 → 27 000 FCFA/sac (+8%) — entre W-1 et P1", 
                       ParagraphStyle('Alert', parent=BODY, fontName='DejaVuSans-Bold', fontSize=9, alignment=TA_CENTER, textColor=RED, spaceAfter=10)))
story.append(Spacer(1, 0.2*cm))

# === 1. GLOBAL — Évolution semaine par semaine ===
story.append(Paragraph("1. Vue Globale — Évolution semaine par semaine", H2))

g_data = [["Période", "Soja (t)", "Conc (t)", "Total (t)", "Soja moy/j (t)", "Conc moy/j (t)", "Ratio soja/conc"]]
for p_name in PERIODS_ORDER:
    p = next(p for p in DATA['periods'] if p['name'] == p_name)
    g = DATA['global'][p_name]
    g_data.append([
        f"{p_name} ({p['dates']['label']})",
        fmt(g['soja_t']), fmt(g['conc_t']), fmt(g['total_t']),
        fmt(g['soja_moy_j']), fmt(g['conc_moy_j']),
        f"{g['ratio']:.2f}:1",
    ])

# Wrap in paragraphs
wrapped_g = []
for ri, row in enumerate(g_data):
    prow = []
    for ci, cell in enumerate(row):
        if ri == 0:
            prow.append(wrap_cell(cell, CELL_HEADER))
        elif ci == 0:
            prow.append(wrap_cell(cell, CELL_LEFT))
        else:
            prow.append(wrap_cell(cell, CELL_CENTER))
    wrapped_g.append(prow)

t1 = Table(wrapped_g, colWidths=[3.5*cm, 1.8*cm, 1.8*cm, 1.8*cm, 2*cm, 2*cm, 2*cm], repeatRows=1)
t1.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), NAVY),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('GRID', (0,0), (-1,-1), 0.5, colors.gray),
    ('TOPPADDING', (0,0), (-1,-1), 5), ('BOTTOMPADDING', (0,0), (-1,-1), 5),
    ('LEFTPADDING', (0,0), (-1,-1), 4), ('RIGHTPADDING', (0,0), (-1,-1), 4),
    # Highlight P1 row (last row) in yellow
    ('BACKGROUND', (0,4), (-1,4), colors.HexColor('#FFF2CC')),
    ('FONT', (0,4), (-1,4), 'DejaVuSans-Bold', 8),
]))
story.append(t1)
story.append(Spacer(1, 0.3*cm))

# Trend week-over-week
story.append(Paragraph("<b>Variation % vs semaine précédente</b>", H3))
trend_data = [["Transition", "Δ Soja %", "Δ Conc %", "Δ Total %", "Lecture"]]
transitions = [
    ('W-3 → W-2', 'W-3', 'W-2'),
    ('W-2 → W-1', 'W-2', 'W-1'),
    ('W-1 → P1 (post-hausse)', 'W-1', 'P1'),
]
trend_summary = []
for label, prev, curr in transitions:
    n_prev = DATA['global'][prev]
    n_curr = DATA['global'][curr]
    var_s = (n_curr['soja_t']/n_prev['soja_t'] - 1)*100 if n_prev['soja_t'] > 0 else 0
    var_c = (n_curr['conc_t']/n_prev['conc_t'] - 1)*100 if n_prev['conc_t'] > 0 else 0
    var_t = (n_curr['total_t']/n_prev['total_t'] - 1)*100 if n_prev['total_t'] > 0 else 0
    lecture = "Hausse" if var_t > 5 else ("Baisse" if var_t < -5 else "Stable")
    if 'P1' in label and var_s < 0:
        lecture = "Chute soja (effet hausse prix)"
    elif 'W-2 → W-1' in label:
        lecture = "Chute majeure soja (normalisation post-pic)"
    elif 'W-3 → W-2' in label:
        lecture = "Pic soja (rupture concurrente)"
    trend_data.append([label, fmt_signed(var_s), fmt_signed(var_c), fmt_signed(var_t), lecture])
    trend_summary.append((label, var_s, var_c, var_t))

wrapped_trend = []
for ri, row in enumerate(trend_data):
    prow = []
    for ci, cell in enumerate(row):
        if ri == 0:
            prow.append(wrap_cell(cell, CELL_HEADER))
        elif ci == 0:
            prow.append(wrap_cell(cell, CELL_LEFT))
        else:
            prow.append(wrap_cell(cell, CELL_CENTER))
    wrapped_trend.append(prow)

t1b = Table(wrapped_trend, colWidths=[4*cm, 2.5*cm, 2.5*cm, 2.5*cm, 5.5*cm], repeatRows=1)
style_list_trend = [
    ('BACKGROUND', (0,0), (-1,0), NAVY),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('GRID', (0,0), (-1,-1), 0.5, colors.gray),
    ('TOPPADDING', (0,0), (-1,-1), 4), ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ('LEFTPADDING', (0,0), (-1,-1), 4), ('RIGHTPADDING', (0,0), (-1,-1), 4),
]
for i, (label, var_s, var_c, var_t) in enumerate(trend_summary, 1):
    style_list_trend.append(('BACKGROUND', (1, i), (1, i), color_for_var(var_s)))
    style_list_trend.append(('BACKGROUND', (2, i), (2, i), color_for_var(var_c)))
    style_list_trend.append(('BACKGROUND', (3, i), (3, i), color_for_var(var_t)))
t1b.setStyle(TableStyle(style_list_trend))
story.append(t1b)
story.append(Spacer(1, 0.3*cm))

# === CHART 1: Global volumes (bar chart) ===
story.append(Paragraph("<b>Graphique 1 — Évolution des volumes (Soja vs Concentrés)</b>", H3))
story.append(Image('/home/z/my-project/scripts/charts/chart1_global_volumes.png', width=17*cm, height=9.4*cm))
story.append(Spacer(1, 0.3*cm))

# === CHART 2: Daily trend (line chart) ===
story.append(Paragraph("<b>Graphique 2 — Tendance cadence quotidienne</b>", H3))
story.append(Image('/home/z/my-project/scripts/charts/chart2_daily_trend.png', width=17*cm, height=9.4*cm))
story.append(Spacer(1, 0.3*cm))

# Global analysis
g_p1 = DATA['global']['P1']
g_w1 = DATA['global']['W-1']
g_w2 = DATA['global']['W-2']
g_w3 = DATA['global']['W-3']

glob_analysis = f"""
<b>Lecture globale</b> : La cadence SOJA suit une <b>trajectoire en dents de scie</b> — {fmt(g_w3['soja_moy_j'])} t/j (W-3) → {fmt(g_w2['soja_moy_j'])} t/j (W-2, pic de rupture concurrente) → {fmt(g_w1['soja_moy_j'])} t/j (W-1, normalisation) → <b>{fmt(g_p1['soja_moy_j'])} t/j (P1, post-hausse prix 04/09)</b>. 
Entre W-1 (pré-hausse) et P1 (post-hausse), la cadence soja <b>remonte de +12,9%</b> ({fmt(g_w1['soja_moy_j'])} → {fmt(g_p1['soja_moy_j'])} t/j) — signe que la hausse tarifaire n'a pas provoqué de chute mais plutôt une reprise après la normalisation du pic de W-2. 
La cadence CONCENTRÉS reste plus stable : {fmt(g_w3['conc_moy_j'])} → {fmt(g_w2['conc_moy_j'])} → {fmt(g_w1['conc_moy_j'])} → <b>{fmt(g_p1['conc_moy_j'])} t/j</b> — variation limitée à ±15%. 
Le ratio bundle passe de <b>{g_w2['ratio']:.2f}:1 (W-2, anormal) → {g_w1['ratio']:.2f}:1 (W-1) → {g_p1['ratio']:.2f}:1 (P1)</b> — retour à un cross-sell discipliné.
"""
story.append(Paragraph(glob_analysis, BODY))
story.append(Spacer(1, 0.3*cm))

# === 2. PAR RÉGION ===
story.append(PageBreak())
story.append(Paragraph("2. Vue Régionale — Évolution par région", H2))

for region in ['Ouest', 'Centre', 'Littoral']:
    story.append(Paragraph(f"<b>{region}</b>", H3))
    reg_data = [["Période", "Soja (t)", "Conc (t)", "Total (t)", "Soja moy/j", "Conc moy/j", "Ratio"]]
    for p_name in PERIODS_ORDER:
        r = DATA['regions'][region][p_name]
        ratio = r['soja_t']/r['conc_t'] if r['conc_t'] > 0 else 0
        work_days = next(p['dates']['work_days'] for p in DATA['periods'] if p['name'] == p_name)
        soja_moy = r['soja_t']/work_days
        conc_moy = r['conc_t']/work_days
        total = r['soja_t'] + r['conc_t']
        reg_data.append([p_name, fmt(r['soja_t']), fmt(r['conc_t']), fmt(total), fmt(soja_moy), fmt(conc_moy), f"{ratio:.2f}:1"])
    
    wrapped_reg = []
    for ri, row in enumerate(reg_data):
        prow = []
        for ci, cell in enumerate(row):
            if ri == 0:
                prow.append(wrap_cell(cell, CELL_HEADER))
            elif ci == 0:
                prow.append(wrap_cell(cell, CELL_LEFT))
            else:
                prow.append(wrap_cell(cell, CELL_CENTER))
        wrapped_reg.append(prow)
    
    t_reg = Table(wrapped_reg, colWidths=[1.8*cm, 2*cm, 2*cm, 2*cm, 2.2*cm, 2.2*cm, 1.8*cm], repeatRows=1)
    t_reg.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), NAVY),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.gray),
        ('TOPPADDING', (0,0), (-1,-1), 4), ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING', (0,0), (-1,-1), 4), ('RIGHTPADDING', (0,0), (-1,-1), 4),
        # Highlight P1 row (last row)
        ('BACKGROUND', (0,4), (-1,4), colors.HexColor('#FFF2CC')),
        ('FONT', (0,4), (-1,4), 'DejaVuSans-Bold', 8),
    ]))
    story.append(t_reg)
    story.append(Spacer(1, 0.2*cm))

# Regional analysis
reg_analysis = f"""
<b>Lecture régionale</b> :
<br/>• <b>OUEST</b> (région leader) : soja évolue {fmt(DATA['regions']['Ouest']['W-3']['soja_t'])} → {fmt(DATA['regions']['Ouest']['W-2']['soja_t'])} → {fmt(DATA['regions']['Ouest']['W-1']['soja_t'])} → <b>{fmt(DATA['regions']['Ouest']['P1']['soja_t'])} t</b> (P1). Normalisation progressive. Cross-sell discipliné (ratio 1,7-2,2:1).
<br/>• <b>CENTRE</b> : tendance similaire — soja {fmt(DATA['regions']['Centre']['W-3']['soja_t'])} → {fmt(DATA['regions']['Centre']['P1']['soja_t'])} t, conc stable autour de 75-120 t/semaine.
<br/>• <b>LITTORAL</b> ⚠ : anomalie W-2 avec {fmt(DATA['regions']['Littoral']['W-2']['soja_t'])} t soja (ratio 10,5:1) due au pic NDOBO ({fmt(DATA['agences']['Ndobo']['W-2']['soja_t'])} t). En P1, retour à un ratio normal de 1,95:1.
"""
story.append(Paragraph(reg_analysis, BODY))
story.append(Spacer(1, 0.3*cm))

# === CHART 3: Regional stacked bar ===
story.append(Paragraph("<b>Graphique 3 — Volume total par région sur 4 semaines</b>", H3))
story.append(Image('/home/z/my-project/scripts/charts/chart3_regional_stacked.png', width=17*cm, height=9.4*cm))
story.append(Spacer(1, 0.3*cm))

# === CHART 4: Regional multiples (small multiples) ===
story.append(PageBreak())
story.append(Paragraph("<b>Graphique 4 — Évolution par région (Soja vs Conc)</b>", H3))
story.append(Image('/home/z/my-project/scripts/charts/chart4_region_multiples.png', width=17*cm, height=6*cm))
story.append(Spacer(1, 0.3*cm))

# === 3. PAR AGENCE ===
story.append(PageBreak())
story.append(Paragraph("3. Vue par Agence — Top 15 (par volume P1)", H2))

ag_data = [["Rang", "Agence", "Région", "P1 Soja", "W-1 Soja", "W-2 Soja", "W-3 Soja", "P1 Conc", "W-1 Conc", "W-2 Conc", "W-3 Conc"]]
for i, (ag, info) in enumerate(list(DATA['agences'].items())[:15], 1):
    ag_data.append([
        str(i), ag, info['region'],
        fmt(info['P1']['soja_t']), fmt(info['W-1']['soja_t']), fmt(info['W-2']['soja_t']), fmt(info['W-3']['soja_t']),
        fmt(info['P1']['conc_t']), fmt(info['W-1']['conc_t']), fmt(info['W-2']['conc_t']), fmt(info['W-3']['conc_t']),
    ])

wrapped_ag = []
for ri, row in enumerate(ag_data):
    prow = []
    for ci, cell in enumerate(row):
        if ri == 0:
            prow.append(wrap_cell(cell, CELL_HEADER))
        elif ci == 1:
            prow.append(wrap_cell(cell, CELL_LEFT_SMALL))
        elif ci == 2:
            prow.append(wrap_cell(cell, CELL_LEFT_SMALL))
        else:
            prow.append(wrap_cell(cell, CELL_CENTER))
    wrapped_ag.append(prow)

t3 = Table(wrapped_ag, colWidths=[0.8*cm, 2*cm, 1.3*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm, 1.5*cm], repeatRows=1)
t3.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), NAVY),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('GRID', (0,0), (-1,-1), 0.5, colors.gray),
    ('TOPPADDING', (0,0), (-1,-1), 3), ('BOTTOMPADDING', (0,0), (-1,-1), 3),
    ('LEFTPADDING', (0,0), (-1,-1), 3), ('RIGHTPADDING', (0,0), (-1,-1), 3),
]))
story.append(t3)
story.append(Spacer(1, 0.3*cm))

# === CHART 5: Top agences evolution ===
story.append(Paragraph("<b>Graphique 5 — Top 10 agences : Évolution du volume SOJA</b>", H3))
story.append(Image('/home/z/my-project/scripts/charts/chart5_top_agences.png', width=17*cm, height=8.5*cm))
story.append(Spacer(1, 0.3*cm))

# === CHART 6: Ratio evolution ===
story.append(PageBreak())
story.append(Paragraph("<b>Graphique 6 — Évolution du ratio bundle soja/concentrés</b>", H3))
story.append(Image('/home/z/my-project/scripts/charts/chart6_ratio_evolution.png', width=17*cm, height=9.4*cm))
story.append(Spacer(1, 0.3*cm))

# === 4. Insights ===
story.append(Paragraph("4. Insights & analyse de tendance", H2))

# Compute additional trend indicators
# Trend direction for soja: W-3 → W-2 → W-1 → P1
soja_trend = [DATA['global'][p]['soja_t'] for p in PERIODS_ORDER]
conc_trend = [DATA['global'][p]['conc_t'] for p in PERIODS_ORDER]

insights = [
    f"<b>Tendance SOJA en dents de scie</b> : {fmt(soja_trend[0])} t (W-3) → {fmt(soja_trend[1])} t (W-2, <b>+12,8%</b>) → {fmt(soja_trend[2])} t (W-1, <b>-58,2%</b>) → <b>{fmt(soja_trend[3])} t (P1, +12,9%)</b>. Pas de chute linéaire mais oscillations liées aux pics de rupture (W-2 boosté par rupture concurrente) et normalisation (W-1).",
    f"<b>P1 vs W-1 (post-hausse vs pré-hausse)</b> : <b>+12,9% soja</b> et <b>-6,4% conc</b>. La hausse prix du 04/09 n'a PAS entraîné de chute soja — au contraire, la cadence remonte légèrement. Le conc ralentit légèrement (effet d'entraînement).",
    f"<b>Tendance CONCENTRÉS plus stable</b> : {fmt(conc_trend[0])} → {fmt(conc_trend[1])} → {fmt(conc_trend[2])} → <b>{fmt(conc_trend[3])} t</b>. Variations contenues entre -32% et +48%, avec un point bas en P1 (224,7 t). Le conc subit un effet de.report lié au soja mais sans effondrement.",
    f"<b>Anomalie W-2 (22-27/08)</b> ⚠ : Volume soja anormalement élevé ({fmt(soja_trend[1])} t vs ~400 t pour W-1 et P1). Explication : rupture concurrente pendant cette période, clients se reportant massivement vers BELGOCAM. NDOBO à lui seul a fait {fmt(DATA['agences']['Ndobo']['W-2']['soja_t'])} t (vs 21,2 t en P1).",
    f"<b>Cross-sell bundle préservé</b> : Ratio soja/conc passe de {DATA['global']['W-2']['ratio']:.2f}:1 (anormal, pic W-2) → {DATA['global']['W-1']['ratio']:.2f}:1 → <b>{DATA['global']['P1']['ratio']:.2f}:1</b>. La normalisation du ratio en P1 (2,01:1, sous l'objectif 2,5:1) confirme que la discipline commerciale se maintient malgré le choc prix.",
    f"<b>OUEST = région la plus résiliente</b> : Variations les plus modérées (P1 vs W-1 : +13,5% soja, -10,7% conc). FAMLA reste le pilier national avec {fmt(DATA['agences']['Famla']['P1']['soja_t'])} t soja + {fmt(DATA['agences']['Famla']['P1']['conc_t'])} t conc en P1.",
    f"<b>LITTORAL = région volatile</b> ⚠ : Fortes variations portées par NDOBO (agence qui a fait un pic exceptionnel en W-2). Hors NDOBO, le Littoral est relativement stable mais sous-performant en P1 ({fmt(DATA['regions']['Littoral']['P1']['soja_t'])} t soja, ratio 2,0:1).",
]
for i, ins in enumerate(insights, 1):
    story.append(Paragraph(f"<b>{i}.</b> {ins}", BULLET))
story.append(Spacer(1, 0.3*cm))

# === 5. Conclusion & Recommandations ===
story.append(Paragraph("5. Conclusion & Recommandations", H2))

conclusion = f"""
<b>Conclusion</b> : L'analyse de tendance sur 4 semaines montre que <b>la hausse prix du 04/09 n'a pas provoqué l'effondrement anticipé</b>. 
La cadence SOJA en P1 ({fmt(g_p1['soja_moy_j'])} t/j) est <b>supérieure de +12,9%</b> à W-1 ({fmt(g_w1['soja_moy_j'])} t/j, pré-hausse), 
ce qui suggère que les clients ont déjà intégré le nouveau prix et continuent à acheter. 
La chute observée vs W-3/W-2 ({fmt(g_w3['soja_moy_j'])}/{fmt(g_w2['soja_moy_j'])} t/j) s'explique par la <b>fin de la rupture concurrente</b> 
qui boostait artificiellement les ventes d'août.
"""
story.append(Paragraph(conclusion, BODY))
story.append(Spacer(1, 0.2*cm))

recos = [
    "<b>Maintenir la cadence actuelle</b> — la tendance P1 vs W-1 est positive (+12,9% soja). Si elle se confirme sur 2 semaines supplémentaires, l'objectif septembre (3 850 t soja) reste atteignable.",
    "<b>Surveiller NDOBO</b> — cette agence a fait un volume anormal en W-2 (pic rupture). En P1, retour à la normale mais sous-objectif. Action commerciale ciblée requise.",
    "<b>Cross-sell bundle préservé</b> (ratio 2,01:1 en P1) — poursuivre la discipline, ne pas relâcher l'effort bundle malgré le choc prix.",
    "<b>LITTORAL à surveiller</b> — région volatile, sous-performe en P1. Renforcer le support commercial sur NDOBO, VILLAGE, NKONGSAMBA.",
    "<b>Communication client</b> — l'absence de chute post-hausse prix suggère que la hausse a été bien absorbée. Préparer un argumentaire pour les clients attentistes potentiels.",
    "<b>Actualiser forecast Q4 2026</b> — si la cadence P1 (90 t/j soja, 45 t/j conc) se maintient, projection Q4 = ~6 700 t soja + ~3 350 t conc, à comparer au forecast actuel de 20 051 t soja + 8 730 t conc (le forecast reste dans la fourchette attendue si la cadence remonte en octobre).",
]
for r in recos:
    story.append(Paragraph(f"• {r}", BULLET))
story.append(Spacer(1, 0.3*cm))

# === Footer ===
story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
story.append(Paragraph(
    f"<b>Méthodologie</b> : Comparaison de 4 périodes de 5 jours ouvrés chacune (lun-sam). "
    f"P1 = 05-10/09/2026 (post-hausse prix 27 000 FCFA/sac). "
    f"W-1 = 29/08-03/09/2026 (pré-hausse), W-2 = 22-27/08/2026, W-3 = 15-20/08/2026. "
    f"Sources : dataset_2023_2026.csv pour août + extraction NJS GROUP ERP (36).xlsx du 11/09/2026 pour septembre. "
    f"Volumes Livrées uniquement, clients internes (SPC/PDC/Comptoir) exclus.",
    SMALL))

doc.build(story)
print(f"\n=== PDF GENERATED ===")
print(f"Path: {OUT}")
print(f"Size: {os.path.getsize(OUT)/1024:.0f} KB")
