"""
Rebuild EVERYTHING from scratch in one consistent pass.

This script:
1. Reads the cleaned (Livrées only) source file
2. Extracts per-client aggregates (CA HT total, CA HT Q1, months active,
   targeted Q1, targeted any)
3. Computes Pareto 20/80 (clients contributing ~80% of CA HT)
4. Builds "Clients uniques - check mensuel.xlsx" from scratch with:
   - 6-month purchase check matrix (green ✓)
   - CA Total HT column
   - 20/80 ★ mark column
5. Builds "Clients zero achat - Janv-Mars.xlsx" listing clients who
   did NOT buy any of the 16 targeted products in Jan/Feb/Mar.

Targeted products (16):
- Tourteaux de soja: T102, T1021, T1023, T1024
- BELGO 10%: C102, C1022, C104, C1042, C1043, C1044, C105, C1053, C1054, C1055
- BELGO 5%:  C101, C103
"""
import re
import os
import time
from openpyxl import load_workbook, Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from collections import defaultdict

# ---- Paths ----
SRC = "/home/z/my-project/download/ventes janv a juin 2026 - Livrées uniquement.xlsx"
CHECK_FILE = "/home/z/my-project/download/Clients uniques - check mensuel.xlsx"
ZERO_ACHAT_FILE = "/home/z/my-project/download/Clients zero achat - Janv-Mars.xlsx"

# ---- Constants ----
TARGET_REFS = {
    "T102", "T1021", "T1023", "T1024",                          # Tourteaux de soja
    "C102", "C1022", "C104", "C1042", "C1043", "C1044",         # BELGO 10%
    "C105", "C1053", "C1054", "C1055",                          # BELGO 10% (suite)
    "C101", "C103",                                              # BELGO 5%
}
assert len(TARGET_REFS) == 16

MONTHS = [
    ("Sheet 1", "Janvier", 0),
    ("Feuil1",  "Février", 1),
    ("Feuil2",  "Mars",    2),
    ("Feuil3",  "Avril",   3),
    ("Feuil4",  "Mai",     4),
    ("Feuil5",  "Juin",    5),
]
FIRST_QUARTER_SHEETS = {"Sheet 1", "Feuil1", "Feuil2"}

TIERS_RE = re.compile(r"^\s*([A-Z]{2,}[\w-]*?)\s*-\s+(.+?)\s*$")

def split_tiers(tiers):
    if tiers is None:
        return ("", "")
    s = str(tiers).strip()
    m = TIERS_RE.match(s)
    if m:
        return (m.group(1).strip(), m.group(2).strip())
    return ("", s)

# ---- 1. Read source & aggregate per-client data ---------------------------
print(f"Reading source: {SRC}")
t0 = time.time()
wb_src = load_workbook(SRC, read_only=True, data_only=True)
print(f"  Loaded in {time.time()-t0:.1f}s")

client_ca_total    = defaultdict(float)  # (ref, name) -> total CA HT (6 months)
client_ca_q1       = defaultdict(float)  # (ref, name) -> CA HT Jan-Mar (all products)
client_months      = defaultdict(set)    # (ref, name) -> set of month indices (any product)
client_targeted_q1 = defaultdict(bool)   # bought >=1 targeted product in Q1
client_targeted_any= defaultdict(bool)   # bought >=1 targeted product in any month

for sheet_name, month_label, m_idx in MONTHS:
    ws = wb_src[sheet_name]
    n = 0
    for row in ws.iter_rows(min_row=3, values_only=True):
        tiers = row[5] if len(row) > 5 else None
        if tiers is None or str(tiers).strip() == "":
            continue
        n += 1
        ref_prod = row[0] if len(row) > 0 else None
        ca_ht    = row[8] if len(row) > 8 else 0
        ref_c, name_c = split_tiers(tiers)
        key = (ref_c, name_c)

        try:
            ca_ht_f = float(ca_ht) if ca_ht is not None else 0.0
        except (ValueError, TypeError):
            ca_ht_f = 0.0

        client_ca_total[key] += ca_ht_f
        client_months[key].add(m_idx)

        is_targeted = (ref_prod is not None and str(ref_prod).strip() in TARGET_REFS)
        if is_targeted:
            client_targeted_any[key] = True
            if sheet_name in FIRST_QUARTER_SHEETS:
                client_targeted_q1[key] = True
        if sheet_name in FIRST_QUARTER_SHEETS:
            client_ca_q1[key] += ca_ht_f
    print(f"  {month_label:<10} ({sheet_name}): {n} client occurrences")

wb_src.close()

clients_all = sorted(client_ca_total.keys(), key=lambda k: (k[1].upper(), k[0]))
print(f"\nTotal unique clients: {len(clients_all)}")
total_ca = sum(client_ca_total.values())
print(f"Total CA HT (6 months): {total_ca:,.0f} FCFA")

# ---- 2. Pareto 20/80 -----------------------------------------------------
sorted_by_ca = sorted(clients_all, key=lambda k: -client_ca_total[k])
pareto_threshold = 0.80 * total_ca
pareto_clients = set()
cumulative = 0.0
for key in sorted_by_ca:
    cumulative += client_ca_total[key]
    pareto_clients.add(key)
    if cumulative >= pareto_threshold:
        break

pareto_count = len(pareto_clients)
pareto_pct_clients = pareto_count / len(clients_all) * 100
pareto_ca = sum(client_ca_total[k] for k in pareto_clients)
pareto_pct_ca = pareto_ca / total_ca * 100

print(f"\n{'='*70}")
print(f"PARETO 20/80")
print(f"{'='*70}")
print(f"Pareto clients (top)       : {pareto_count} ({pareto_pct_clients:.1f}% of clients)")
print(f"CA HT generated by them    : {pareto_ca:,.0f} FCFA ({pareto_pct_ca:.1f}% of total CA)")

# ---- 3. Build check file FROM SCRATCH -------------------------------------
print(f"\n{'='*70}")
print(f"Building check file: {CHECK_FILE}")
print(f"{'='*70}")

wb = Workbook()
wb.properties.creator = "Z.ai"
ws = wb.active
ws.title = "Clients uniques"

# ---- Styles ----
TITLE_FONT = Font(name="Calibri", size=14, bold=True, color="1F4E78")
TITLE_ALIGN = Alignment(horizontal="left", vertical="center")
HEADER_FILL = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
HEADER_FONT = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
HEADER_ALIGN = Alignment(horizontal="center", vertical="center", wrap_text=True)
BAND_FILL = PatternFill(start_color="F5F5F5", end_color="F5F5F5", fill_type="solid")
BODY_FONT = Font(name="Calibri", size=10)
BODY_ALIGN_CENTER = Alignment(horizontal="center", vertical="center")
BODY_ALIGN_LEFT = Alignment(horizontal="left", vertical="center")
BODY_ALIGN_RIGHT = Alignment(horizontal="right", vertical="center")
GREEN_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
GREEN_FONT = Font(name="Calibri", size=12, bold=True, color="006100")
CHECK_SYMBOL = "✓"
PARETO_FILL = PatternFill(start_color="FFD966", end_color="FFD966", fill_type="solid")
PARETO_FONT = Font(name="Calibri", size=14, bold=True, color="7F6000")
PARETO_SYMBOL = "★"
CA_NUM_FMT = '#,##0" FCFA"'
THIN = Side(border_style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

# Row 1: Title
ws.cell(row=1, column=1,
        value="BELGOCAM SA - Clients uniques (Janvier - Juin 2026) — Check mensuel d'achats"
).font = TITLE_FONT
ws.cell(row=1, column=1).alignment = TITLE_ALIGN
ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=12)
ws.row_dimensions[1].height = 26

# Row 2: spacer
ws.row_dimensions[2].height = 6

# Row 3: Headers (12 columns)
HEADERS = ["N°", "Réf. client", "Nom du client",
           "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
           "Nb mois d'achat", "CA Total HT (6 mois)", "Catégorie 20/80"]
for col_idx, h in enumerate(HEADERS, start=1):
    c = ws.cell(row=3, column=col_idx, value=h)
    c.fill = HEADER_FILL; c.font = HEADER_FONT
    c.alignment = HEADER_ALIGN; c.border = BORDER
ws.row_dimensions[3].height = 36

# Data rows
START_ROW = 4
n_clients = len(clients_all)
for i, key in enumerate(clients_all, start=1):
    r = START_ROW + i - 1
    ref, name = key
    banding = (i % 2 == 0)
    months_active = client_months.get(key, set())

    # N°
    c = ws.cell(row=r, column=1, value=i)
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_CENTER; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # Réf. client
    c = ws.cell(row=r, column=2, value=ref)
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_CENTER; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # Nom du client
    c = ws.cell(row=r, column=3, value=name)
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_LEFT; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # Month checks (cols 4..9)
    for m_idx in range(6):
        col = 4 + m_idx
        c = ws.cell(row=r, column=col)
        c.border = BORDER
        c.alignment = BODY_ALIGN_CENTER
        if m_idx in months_active:
            c.value = CHECK_SYMBOL
            c.fill = GREEN_FILL
            c.font = GREEN_FONT
        else:
            if banding: c.fill = BAND_FILL
            c.font = BODY_FONT

    # Nb mois d'achat
    c = ws.cell(row=r, column=10, value=len(months_active))
    c.font = Font(name="Calibri", size=10, bold=True)
    c.alignment = BODY_ALIGN_CENTER; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # CA Total HT (6 mois)
    c = ws.cell(row=r, column=11, value=client_ca_total.get(key, 0.0))
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_RIGHT; c.border = BORDER
    c.number_format = CA_NUM_FMT
    if banding: c.fill = BAND_FILL

    # Catégorie 20/80
    c = ws.cell(row=r, column=12)
    c.border = BORDER
    c.alignment = BODY_ALIGN_CENTER
    if key in pareto_clients:
        c.value = PARETO_SYMBOL
        c.fill = PARETO_FILL
        c.font = PARETO_FONT
    else:
        if banding: c.fill = BAND_FILL
        c.font = BODY_FONT

# Column widths
ws.column_dimensions['A'].width = 6
ws.column_dimensions['B'].width = 16
ws.column_dimensions['C'].width = 42
for col_letter in ['D', 'E', 'F', 'G', 'H', 'I']:
    ws.column_dimensions[col_letter].width = 11
ws.column_dimensions['J'].width = 16
ws.column_dimensions['K'].width = 22
ws.column_dimensions['L'].width = 14

# Freeze panes
ws.freeze_panes = "D4"
# Auto filter
ws.auto_filter.ref = f"A3:L{START_ROW + n_clients - 1}"

wb.save(CHECK_FILE)
print(f"  Saved: {CHECK_FILE}")
print(f"  File size: {os.path.getsize(CHECK_FILE):,} bytes")

# ---- 4. Build zero-achat (Jan-Mar) file ----------------------------------
print(f"\n{'='*70}")
print(f"Building zero-achat file: {ZERO_ACHAT_FILE}")
print(f"{'='*70}")

zero_achat_clients = [k for k in clients_all if not client_targeted_q1[k]]
zero_achat_clients.sort(key=lambda k: (k[1].upper(), k[0]))

print(f"Total clients              : {len(clients_all)}")
print(f"Clients with targeted Q1   : {len(clients_all) - len(zero_achat_clients)}")
print(f"Clients 'zero achat' Q1    : {len(zero_achat_clients)}")

wb = Workbook()
wb.properties.creator = "Z.ai"
ws = wb.active
ws.title = "Zero achat Q1"

# Title row 1
ws.cell(row=1, column=1,
        value=("BELGOCAM SA - Clients 'zéro achat' Janvier-Mars 2026 "
               "(Tourteaux de soja + BELGO 10% + BELGO 5%)")
).font = TITLE_FONT
ws.cell(row=1, column=1).alignment = TITLE_ALIGN
ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=8)
ws.row_dimensions[1].height = 26

# Row 2: criteria explanation
SUB_FONT = Font(name="Calibri", size=10, italic=True, color="595959")
ws.cell(row=2, column=1,
        value=("Critère : client n'ayant acheté AUCUN des 16 produits ciblés "
               "(4 tourteaux de soja + 10 BELGO 10% + 2 BELGO 5%) en janvier, février ou mars 2026.")
).font = SUB_FONT
ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=8)
ws.row_dimensions[2].height = 22

# Row 3: Headers
HEADERS = ["N°", "Réf. client", "Nom du client",
           "Achat ciblé Q1 ?", "CA HT Q1 (tous produits)",
           "Achat ciblé 6 mois ?", "CA HT total 6 mois", "Catégorie 20/80"]
for col_idx, h in enumerate(HEADERS, start=1):
    c = ws.cell(row=3, column=col_idx, value=h)
    c.fill = HEADER_FILL; c.font = HEADER_FONT
    c.alignment = HEADER_ALIGN; c.border = BORDER
ws.row_dimensions[3].height = 36

# Data rows
for i, key in enumerate(zero_achat_clients, start=1):
    r = 3 + i
    ref, name = key
    banding = (i % 2 == 0)

    # N°
    c = ws.cell(row=r, column=1, value=i)
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_CENTER; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # Réf
    c = ws.cell(row=r, column=2, value=ref)
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_CENTER; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # Nom
    c = ws.cell(row=r, column=3, value=name)
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_LEFT; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # Achat ciblé Q1 ?
    c = ws.cell(row=r, column=4, value="Non")
    c.font = Font(name="Calibri", size=10, color="C00000", bold=True)
    c.alignment = BODY_ALIGN_CENTER; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # CA HT Q1 (tous produits)
    c = ws.cell(row=r, column=5, value=client_ca_q1.get(key, 0.0))
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_RIGHT; c.border = BORDER
    c.number_format = CA_NUM_FMT
    if banding: c.fill = BAND_FILL

    # Achat ciblé 6 mois ?
    targeted_any = client_targeted_any.get(key, False)
    c = ws.cell(row=r, column=6, value=("Oui" if targeted_any else "Non"))
    if targeted_any:
        c.font = Font(name="Calibri", size=10, color="006100", bold=True)
    else:
        c.font = Font(name="Calibri", size=10, color="C00000", bold=True)
    c.alignment = BODY_ALIGN_CENTER; c.border = BORDER
    if banding: c.fill = BAND_FILL

    # CA HT total 6 mois
    c = ws.cell(row=r, column=7, value=client_ca_total.get(key, 0.0))
    c.font = BODY_FONT; c.alignment = BODY_ALIGN_RIGHT; c.border = BORDER
    c.number_format = CA_NUM_FMT
    if banding: c.fill = BAND_FILL

    # 20/80 marker
    c = ws.cell(row=r, column=8)
    c.border = BORDER
    c.alignment = BODY_ALIGN_CENTER
    if key in pareto_clients:
        c.value = PARETO_SYMBOL
        c.fill = PARETO_FILL
        c.font = PARETO_FONT
    else:
        if banding: c.fill = BAND_FILL
        c.font = BODY_FONT

# Column widths
ws.column_dimensions['A'].width = 6
ws.column_dimensions['B'].width = 16
ws.column_dimensions['C'].width = 48
ws.column_dimensions['D'].width = 16
ws.column_dimensions['E'].width = 22
ws.column_dimensions['F'].width = 18
ws.column_dimensions['G'].width = 22
ws.column_dimensions['H'].width = 14

ws.freeze_panes = "D4"
ws.auto_filter.ref = f"A3:H{3 + len(zero_achat_clients)}"

wb.save(ZERO_ACHAT_FILE)
print(f"  Saved: {ZERO_ACHAT_FILE}")
print(f"  File size: {os.path.getsize(ZERO_ACHAT_FILE):,} bytes")

# ---- 5. Summary ----------------------------------------------------------
print(f"\n{'='*70}")
print(f"SUMMARY")
print(f"{'='*70}")
targeted_any_count = sum(1 for k in zero_achat_clients if client_targeted_any[k])
never_targeted = sum(1 for k in zero_achat_clients if not client_targeted_any[k])
pareto_in_zero = sum(1 for k in zero_achat_clients if k in pareto_clients)
print(f"  Total unique clients (6 mois)            : {len(clients_all)}")
print(f"  Total CA HT (6 mois)                     : {total_ca:,.0f} FCFA")
print(f"  Clients Pareto (top {pareto_pct_clients:.1f}%)                  : {pareto_count} ({pareto_pct_ca:.1f}% du CA)")
print(f"  Clients 'zero achat' Q1 (Jan-Mar)        : {len(zero_achat_clients)}")
print(f"    dont acquisition ciblée APRÈS mars     : {targeted_any_count}")
print(f"    dont JAMAIS acheté de produit ciblé    : {never_targeted}")
print(f"    dont font partie du 20/80              : {pareto_in_zero}")
